# Generated by Django 6.0.1 on 2026-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
